% Define images to process
imageFileNames = {
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010329.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010334.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010340.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010345.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010350.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010400.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010406.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010420.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010433.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010452.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010507.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010516.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010527.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010559.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010635.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010658.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010808.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010819.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010830.jpg',...
    'F:\UNIVERSITY\4TH_SEM\3 EN2550 - Fundamentals of Image Processing and Machine Vision\Computer-Vision-and-Image-Processing\SINGLE VIEW GEOMETRY\Camera Calibration\huawei-y5-2017-phone-cam\IMG_20210417_010845.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 30;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
